version: '3'

services:
  whatsapp-core-db:
    image: postgres:latest
    container_name: whatsapp-core-db
    restart: always
    tty: true
    volumes:
      - .volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    env_file:
      - .env